/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_adapter_gpio.h"
#include "pin_mux.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* gpio_io, 02 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PIN_LEVEL 0U
/* gpio_io, 03 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PIN_LEVEL 1U
/* gpio_io, 09 signal defines */
/* Definition of the pin direction */
#define BOARD_INITENET_ENET_RST_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_INITENET_ENET_RST_PIN_LEVEL 1U
/* gpio_io, 10 signal defines */
/* Definition of the pin direction */
#define BOARD_INITENET_PHY_INTR_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_INITENET_PHY_INTR_PIN_LEVEL 0U
/* Definition of the pin trigger mode */
#define BOARD_INITENET_PHY_INTR_TRIGGER_MODE kHAL_GpioInterruptLogicZero
/* gpio_io, 11 signal defines */
/* Definition of the pin direction */
#define BOARD_I2C1_PINS_Interrupt_Temp_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_I2C1_PINS_Interrupt_Temp_PIN_LEVEL 0U
/* gpio_io, 15 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN_LEVEL 0U
/* gpio_io, 20 signal defines */
/* Definition of the pin direction */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN_LEVEL 0U
/* gpio_io, 21 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN_LEVEL 1U
/* gpio_io, 22 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_A1_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_A1_PIN_LEVEL 0U
/* gpio_io, 23 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_A0_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_A0_PIN_LEVEL 0U
/* gpio_io, 24 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_A2_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_A2_PIN_LEVEL 0U
/* gpio_io, 25 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN_LEVEL 1U
/* gpio_io, 27 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN_DIRECTION kHAL_GpioDirectionIn
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN_LEVEL 0U
/* Definition of the pin trigger mode */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_TRIGGER_MODE kHAL_GpioInterruptFallingEdge
/* gpio_io, 04 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN_LEVEL 1U
/* gpio_io, 06 signal defines */
/* Definition of the pin direction */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN_DIRECTION kHAL_GpioDirectionOut
/* Definition of the pin level after initialization */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN_LEVEL 1U

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_LE_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_OE_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITENET_ENET_RST_handle);
extern GPIO_HANDLE_DEFINE(BOARD_INITENET_PHY_INTR_handle);
extern GPIO_HANDLE_DEFINE(BOARD_I2C1_PINS_Interrupt_Temp_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_handle);
extern GPIO_HANDLE_DEFINE(BOARD_UART_DEBUG_PINS_UART1_TX_EN_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A1_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A0_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A2_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_handle);
extern GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_handle);

/***********************************************************************************************************************
 * Global functions
 **********************************************************************************************************************/
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
