/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MIMXRT1064xxxxA
package_id: MIMXRT1064DVL6A
mcu_data: ksdk2_0
processor_version: 24.12.10
board: MIMXRT1064-EVK
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 1c6563a6-c68b-40e5-8828-2853c99f95fa
  called_from_default_init: true
  id_prefix: BOARD_
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - commonSetting:
    - HAL_GPIO_ISR_PRIORITY: '3'
    - HAL_GpioPreInit: 'true'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void BOARD_NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'igpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
      - 13: []
      - 14: []
      - 15: []
      - 16: []
      - 17: []
      - 18: []
      - 19: []
      - 20: []
      - 21: []
      - 22: []
      - 23: []
      - 24: []
      - 25: []
      - 26: []
      - 27: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level){
  hal_gpio_pin_config_t temp;
  /* Array of GPIO peripheral base address. */
  static GPIO_Type *const s_gpioBases[] = GPIO_BASE_PTRS;
  uint8_t portInd;
  /* Find the port index from base address mappings. */
  for (portInd = 0U; portInd < ARRAY_SIZE(s_gpioBases); portInd++)
  {    if (s_gpioBases[portInd] == port)
    {
      break;
    }
  }
  
  assert(portInd < ARRAY_SIZE(s_gpioBases));
  
  temp.direction = direction;
  temp.level = level;
  temp.port = portInd;
  temp.pin = pin;
  
  return temp;
};
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_LE_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_OE_handle);
GPIO_HANDLE_DEFINE(BOARD_INITENET_ENET_RST_handle);
GPIO_HANDLE_DEFINE(BOARD_INITENET_PHY_INTR_handle);
GPIO_HANDLE_DEFINE(BOARD_I2C1_PINS_Interrupt_Temp_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_handle);
GPIO_HANDLE_DEFINE(BOARD_UART_DEBUG_PINS_UART1_TX_EN_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A1_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A0_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_A2_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_handle);

static void BOARD_GPIO1_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* gpio_io, 02 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_LE_PORT, BOARD_LPSPI1_LED_PINS_LED_LE_PIN, BOARD_LPSPI1_LED_PINS_LED_LE_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_LE_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_LE_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 03 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_OE_PORT, BOARD_LPSPI1_LED_PINS_LED_OE_PIN, BOARD_LPSPI1_LED_PINS_LED_OE_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_OE_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_OE_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 09 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITENET_ENET_RST_PORT, BOARD_INITENET_ENET_RST_PIN, BOARD_INITENET_ENET_RST_PIN_DIRECTION, BOARD_INITENET_ENET_RST_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITENET_ENET_RST_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 10 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITENET_PHY_INTR_PORT, BOARD_INITENET_PHY_INTR_PIN, BOARD_INITENET_PHY_INTR_PIN_DIRECTION, BOARD_INITENET_PHY_INTR_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITENET_PHY_INTR_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioSetTriggerMode(BOARD_INITENET_PHY_INTR_handle, BOARD_INITENET_PHY_INTR_TRIGGER_MODE);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 11 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_I2C1_PINS_Interrupt_Temp_PORT, BOARD_I2C1_PINS_Interrupt_Temp_PIN, BOARD_I2C1_PINS_Interrupt_Temp_PIN_DIRECTION, BOARD_I2C1_PINS_Interrupt_Temp_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_I2C1_PINS_Interrupt_Temp_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 15 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PORT, BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN, BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 20 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_UART_DEBUG_PINS_UART1_TX_EN_PORT, BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN, BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN_DIRECTION, BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_UART_DEBUG_PINS_UART1_TX_EN_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 21 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PORT, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 22 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_A1_PORT, BOARD_LPSPI1_LED_PINS_A1_PIN, BOARD_LPSPI1_LED_PINS_A1_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_A1_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_A1_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 23 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_A0_PORT, BOARD_LPSPI1_LED_PINS_A0_PIN, BOARD_LPSPI1_LED_PINS_A0_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_A0_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_A0_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 24 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_A2_PORT, BOARD_LPSPI1_LED_PINS_A2_PIN, BOARD_LPSPI1_LED_PINS_A2_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_A2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_A2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 25 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PORT, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 27 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PORT, BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN, BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioSetTriggerMode(BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_handle, BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_TRIGGER_MODE);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * GPIO8 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO8'
- type: 'igpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_adapter_1.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO8'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
    - gpioPinsConfig: []
    - globalCfg: []
    - differentPeripheralsAdd: []
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_handle);
GPIO_HANDLE_DEFINE(BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_handle);

static void BOARD_GPIO8_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* gpio_io, 04 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PORT, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 06 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PORT, BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN, BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN_DIRECTION, BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  /* GPIO adapter pre-initialization */
  HAL_GpioPreInit();

  /* Initialize components */
  BOARD_GPIO1_init();
  BOARD_GPIO8_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
