/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_TXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_TXD_SIGNAL                                 TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_RXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_RXD_SIGNAL                                 RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

/* GPIO_EMC_09 (coord C2), SEMC_A0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A0_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_10 (coord G1), SEMC_A1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A1_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_11 (coord G3), SEMC_A2 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A2_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A2_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_12 (coord H1), SEMC_A3 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A3_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A3_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_13 (coord A6), SEMC_A4 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A4_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A4_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A4_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_14 (coord B6), SEMC_A5 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A5_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A5_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A5_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_15 (coord B1), SEMC_A6 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A6_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A6_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A6_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_16 (coord A5), SEMC_A7 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A7_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A7_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A7_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_17 (coord A4), SEMC_A8 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A8_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A8_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A8_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_18 (coord B2), SEMC_A9 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A9_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A9_SIGNAL                                      ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A9_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_23 (coord G2), SEMC_A10 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A10_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A10_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A10_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_EMC_19 (coord B4), SEMC_A11 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A11_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A11_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A11_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_EMC_20 (coord A3), SEMC_A12 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_A12_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_A12_SIGNAL                                     ADDR   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_A12_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_EMC_21 (coord C1), SEMC_BA0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_BA0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_BA0_SIGNAL                                       BA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_BA0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_22 (coord F1), SEMC_BA1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_BA1_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_BA1_SIGNAL                                       BA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_BA1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_EMC_24 (coord D3), SEMC_CAS */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CAS_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CAS_SIGNAL                                 semc_cas   /*!< Signal name */

/* GPIO_EMC_27 (coord A2), SEMC_CKE */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CKE_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CKE_SIGNAL                                 semc_cke   /*!< Signal name */

/* GPIO_EMC_26 (coord B3), SEMC_CLK */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_CLK_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_CLK_SIGNAL                                 semc_clk   /*!< Signal name */

/* GPIO_EMC_00 (coord E3), SEMC_D0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D0_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D0_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D0_CHANNEL                                       0U   /*!< Signal channel */

/* GPIO_EMC_01 (coord F3), SEMC_D1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D1_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D1_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D1_CHANNEL                                       1U   /*!< Signal channel */

/* GPIO_EMC_02 (coord F4), SEMC_D2 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D2_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D2_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D2_CHANNEL                                       2U   /*!< Signal channel */

/* GPIO_EMC_03 (coord G4), SEMC_D3 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D3_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D3_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D3_CHANNEL                                       3U   /*!< Signal channel */

/* GPIO_EMC_04 (coord F2), SEMC_D4 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D4_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D4_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D4_CHANNEL                                       4U   /*!< Signal channel */

/* GPIO_EMC_05 (coord G5), SEMC_D5 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D5_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D5_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D5_CHANNEL                                       5U   /*!< Signal channel */

/* GPIO_EMC_06 (coord H5), SEMC_D6 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D6_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D6_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D6_CHANNEL                                       6U   /*!< Signal channel */

/* GPIO_EMC_07 (coord H4), SEMC_D7 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D7_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D7_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D7_CHANNEL                                       7U   /*!< Signal channel */

/* GPIO_EMC_30 (coord C6), SEMC_D8 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D8_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D8_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D8_CHANNEL                                       8U   /*!< Signal channel */

/* GPIO_EMC_31 (coord C5), SEMC_D9 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D9_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D9_SIGNAL                                      DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D9_CHANNEL                                       9U   /*!< Signal channel */

/* GPIO_EMC_32 (coord D5), SEMC_D10 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D10_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D10_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D10_CHANNEL                                     10U   /*!< Signal channel */

/* GPIO_EMC_33 (coord C4), SEMC_D11 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D11_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D11_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D11_CHANNEL                                     11U   /*!< Signal channel */

/* GPIO_EMC_34 (coord D4), SEMC_D12 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D12_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D12_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D12_CHANNEL                                     12U   /*!< Signal channel */

/* GPIO_EMC_35 (coord E5), SEMC_D13 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D13_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D13_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D13_CHANNEL                                     13U   /*!< Signal channel */

/* GPIO_EMC_36 (coord C3), SEMC_D14 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D14_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D14_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D14_CHANNEL                                     14U   /*!< Signal channel */

/* GPIO_EMC_37 (coord E4), SEMC_D15 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_D15_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_D15_SIGNAL                                     DATA   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_D15_CHANNEL                                     15U   /*!< Signal channel */

/* GPIO_EMC_08 (coord H3), SEMC_DM0 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_DM0_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_DM0_SIGNAL                                       DM   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_DM0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_EMC_38 (coord D6), SEMC_DM1 */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_DM1_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_DM1_SIGNAL                                       DM   /*!< Signal name */
#define BOARD_INITSDRAM_SEMC_DM1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_EMC_25 (coord D2), SEMC_RAS */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_RAS_PERIPHERAL                                 SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_RAS_SIGNAL                                 semc_ras   /*!< Signal name */

/* GPIO_EMC_28 (coord D1), SEMC_WE */
/* Routed pin properties */
#define BOARD_INITSDRAM_SEMC_WE_PERIPHERAL                                  SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_SEMC_WE_SIGNAL                                   semc_we   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITSDRAM_ENET_MDIO_PERIPHERAL                                SEMC   /*!< Peripheral name */
#define BOARD_INITSDRAM_ENET_MDIO_SIGNAL                                     CSX   /*!< Signal name */
#define BOARD_INITSDRAM_ENET_MDIO_CHANNEL                                     0U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDRAM(void);

#define BOARD_INITLCD_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x80000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B0_05 (coord B8), LCDIF_D1/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D1_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D1_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_B0_06 (coord A8), LCDIF_D2/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D2_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D2_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_B0_00 (coord D7), LCDIF_CLK */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_CLK_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_CLK_SIGNAL                                 lcdif_clk   /*!< Signal name */

/* GPIO_B0_07 (coord A9), LCDIF_D3/BT_CFG[3] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D3_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D3_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_B0_08 (coord B9), LCDIF_D4/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D4_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D4_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D4_CHANNEL                                        4U   /*!< Signal channel */

/* GPIO_B0_10 (coord D9), LCDIF_D6/BT_CFG[6] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D6_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D6_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D6_CHANNEL                                        6U   /*!< Signal channel */

/* GPIO_B0_11 (coord A10), LCDIF_D7/BT_CFG[7] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D7_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D7_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D7_CHANNEL                                        7U   /*!< Signal channel */

/* GPIO_B0_12 (coord C10), LCDIF_D8/BT_CFG[8] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D8_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D8_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D8_CHANNEL                                        8U   /*!< Signal channel */

/* GPIO_B0_13 (coord D10), LCDIF_D9/BT_CFG[9] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D9_PERIPHERAL                                  LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D9_SIGNAL                                 lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D9_CHANNEL                                        9U   /*!< Signal channel */

/* GPIO_B0_14 (coord E10), LCDIF_D10/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D10_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D10_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D10_CHANNEL                                      10U   /*!< Signal channel */

/* GPIO_B0_15 (coord E11), LCDIF_D11/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D11_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D11_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D11_CHANNEL                                      11U   /*!< Signal channel */

/* GPIO_B1_00 (coord A11), LCDIF_D12 */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D12_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D12_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D12_CHANNEL                                      12U   /*!< Signal channel */

/* GPIO_B1_01 (coord B11), LCDIF_D13 */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D13_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D13_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D13_CHANNEL                                      13U   /*!< Signal channel */

/* GPIO_B1_02 (coord C11), LCDIF_D14 */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_D14_PERIPHERAL                                 LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_D14_SIGNAL                                lcdif_data   /*!< Signal name */
#define BOARD_INITLCD_LCDIF_D14_CHANNEL                                      14U   /*!< Signal channel */

/* GPIO_B0_01 (coord E7), LCDIF_ENABLE */
/* Routed pin properties */
#define BOARD_INITLCD_LCDIF_ENABLE_PERIPHERAL                              LCDIF   /*!< Peripheral name */
#define BOARD_INITLCD_LCDIF_ENABLE_SIGNAL                           lcdif_enable   /*!< Signal name */

/* GPIO_B1_15 (coord B14), USB_HOST_PWR/BACKLIGHT_CTL */
/* Routed pin properties */
#define BOARD_INITLCD_BACKLIGHT_CTL_PERIPHERAL                             GPIO2   /*!< Peripheral name */
#define BOARD_INITLCD_BACKLIGHT_CTL_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITLCD_BACKLIGHT_CTL_CHANNEL                                  31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLCD_BACKLIGHT_CTL_GPIO                                   GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITLCD_BACKLIGHT_CTL_GPIO_PIN                                 31U   /*!< GPIO pin number */
#define BOARD_INITLCD_BACKLIGHT_CTL_GPIO_PIN_MASK                    (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITLCD_BACKLIGHT_CTL_PORT                                   GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITLCD_BACKLIGHT_CTL_PIN                                      31U   /*!< PORT pin number */
#define BOARD_INITLCD_BACKLIGHT_CTL_PIN_MASK                         (1U << 31U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLCD(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCAN(void);

#define BOARD_INITENET_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0600U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_INITENET_ENET_MDC_PERIPHERAL                                  ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_MDC_SIGNAL                                  enet_mdc   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITENET_ENET_MDIO_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_MDIO_SIGNAL                                enet_mdio   /*!< Signal name */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TX_CLK_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TX_CLK_SIGNAL                           enet_ref_clk   /*!< Signal name */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXD0_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_RXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXD1_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_RXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_06 (coord C12), ENET_CRS_DV */
/* Routed pin properties */
#define BOARD_INITENET_ENET_CRS_DV_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_CRS_DV_SIGNAL                             enet_rx_en   /*!< Signal name */

/* GPIO_B1_11 (coord C13), ENET_RXER */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXER_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXER_SIGNAL                               enet_rx_er   /*!< Signal name */

/* GPIO_B1_07 (coord B12), ENET_TXD0 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXD0_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_TXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_08 (coord A12), ENET_TXD1 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXD1_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_TXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_09 (coord A13), ENET_TXEN */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXEN_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXEN_SIGNAL                               enet_tx_en   /*!< Signal name */

/* GPIO_AD_B0_09 (coord F14), RS485_DIRECTION_ENABLE/JTAG_TDI/J21[5]/ENET_RST/J22[5]/JTAG_TDI/J21[5]/ENET_RST/J22[5] */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RST_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RST_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITENET_ENET_RST_CHANNEL                                       9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_ENET_RST_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITENET_ENET_RST_INIT_GPIO_VALUE                               1U   /*!< GPIO output initial state */
#define BOARD_INITENET_ENET_RST_GPIO_PIN                                      9U   /*!< GPIO pin number */
#define BOARD_INITENET_ENET_RST_GPIO_PIN_MASK                         (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_INITENET_ENET_RST_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITENET_ENET_RST_PIN                                           9U   /*!< PORT pin number */
#define BOARD_INITENET_ENET_RST_PIN_MASK                              (1U << 9U)   /*!< PORT pin mask */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
/* Routed pin properties */
#define BOARD_INITENET_PHY_INTR_PERIPHERAL                                 GPIO1   /*!< Peripheral name */
#define BOARD_INITENET_PHY_INTR_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITENET_PHY_INTR_CHANNEL                                      10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITENET_PHY_INTR_GPIO                                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITENET_PHY_INTR_GPIO_PIN                                     10U   /*!< GPIO pin number */
#define BOARD_INITENET_PHY_INTR_GPIO_PIN_MASK                        (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITENET_PHY_INTR_PORT                                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITENET_PHY_INTR_PIN                                          10U   /*!< PORT pin number */
#define BOARD_INITENET_PHY_INTR_PIN_MASK                             (1U << 10U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENET(void);

/* GPIO_SD_B0_01 (coord J3), J24_3_CS */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_CLK_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_CLK_SIGNAL                                 usdhc_clk   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSDHC(void);

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_CLK_PERIPHERAL                      FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_CLK_SIGNAL                   FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_D2_A_PERIPHERAL                     FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_D2_A_SIGNAL                 FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_D0_A_PERIPHERAL                     FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_D0_A_SIGNAL                 FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_D1_A_PERIPHERAL                     FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_D1_A_SIGNAL                 FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_03 (coord M4), FlexSPI_D0_B */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_D0_B_PERIPHERAL                     FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_D0_B_SIGNAL                 FLEXSPI_B_DATA0   /*!< Signal name */

/* GPIO_SD_B1_06 (coord L3), DisableQSPI */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_SS0_PERIPHERAL                      FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_SS0_SIGNAL                  FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_D3_A_PERIPHERAL                     FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_D3_A_SIGNAL                 FLEXSPI_A_DATA3   /*!< Signal name */

/* GPIO_SD_B1_05 (coord N3), FlexSPI_DQS */
/* Routed pin properties */
#define BOARD_INITHYPERFLASH_FlexSPI_DQS_PERIPHERAL                      FLEXSPI   /*!< Peripheral name */
#define BOARD_INITHYPERFLASH_FlexSPI_DQS_SIGNAL                    FLEXSPI_A_DQS   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitHyperFlash(void);

#define BOARD_INITPINSCTS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x10U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* WAKEUP (coord L6), SD_PWREN/USER_BT/SD_PWREN/SD_PWREN */
/* Routed pin properties */
#define BOARD_INITPINSCTS_USER_BT_PERIPHERAL                               GPIO5   /*!< Peripheral name */
#define BOARD_INITPINSCTS_USER_BT_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINSCTS_USER_BT_CHANNEL                                     0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINSCTS_USER_BT_GPIO                                     GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINSCTS_USER_BT_GPIO_PIN                                    0U   /*!< GPIO pin number */
#define BOARD_INITPINSCTS_USER_BT_GPIO_PIN_MASK                       (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINSCTS_USER_BT_PORT                                     GPIO5   /*!< PORT peripheral base pointer */
#define BOARD_INITPINSCTS_USER_BT_PIN                                         0U   /*!< PORT pin number */
#define BOARD_INITPINSCTS_USER_BT_PIN_MASK                            (1U << 0U)   /*!< PORT pin mask */

/* GPIO_B0_04 (coord C8), LCDIF_D0/BT_CFG[0]/LCDIF_D0/BT_CFG[0]/CPU_LED/LCDIF_D0/BT_CFG[0]/LCDIF_D0/BT_CFG[0]/LCDIF_D0/BT_CFG[0]/LCDIF_D0/BT_CFG[0] */
/* Routed pin properties */
#define BOARD_INITPINSCTS_CPU_LED_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINSCTS_CPU_LED_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINSCTS_CPU_LED_CHANNEL                                     4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINSCTS_CPU_LED_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINSCTS_CPU_LED_INIT_GPIO_VALUE                             0U   /*!< GPIO output initial state */
#define BOARD_INITPINSCTS_CPU_LED_GPIO_PIN                                    4U   /*!< GPIO pin number */
#define BOARD_INITPINSCTS_CPU_LED_GPIO_PIN_MASK                       (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITPINSCTS_CPU_LED_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINSCTS_CPU_LED_PIN                                         4U   /*!< PORT pin number */
#define BOARD_INITPINSCTS_CPU_LED_PIN_MASK                            (1U << 4U)   /*!< PORT pin mask */

/* GPIO_B1_13 (coord D14), WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINSCTS_WDOG_B_PERIPHERAL                                WDOG1   /*!< Peripheral name */
#define BOARD_INITPINSCTS_WDOG_B_SIGNAL                                   wdog_b   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPinsCTS(void);

#define BOARD_ENET1PINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x4000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_ENET1PINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x10000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_MDC_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_MDC_SIGNAL                                 enet_mdc   /*!< Signal name */

/* GPIO_B1_08 (coord A12), ENET_TXD1 */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_TXD1_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_TXD1_SIGNAL                            enet_tx_data   /*!< Signal name */
#define BOARD_ENET1PINS_ENET_TXD1_CHANNEL                                     1U   /*!< Signal channel */

/* GPIO_B1_09 (coord A13), ENET_TXEN */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_TXEN_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_TXEN_SIGNAL                              enet_tx_en   /*!< Signal name */

/* GPIO_B1_07 (coord B12), ENET_TXD0 */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_TXD0_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_TXD0_SIGNAL                            enet_tx_data   /*!< Signal name */
#define BOARD_ENET1PINS_ENET_TXD0_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_B1_10 (coord B13), ENET_TX_CLK */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_TX_CLK_PERIPHERAL                              ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_TX_CLK_SIGNAL                           enet_tx_clk   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_MDIO_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_MDIO_SIGNAL                               enet_mdio   /*!< Signal name */

/* GPIO_B1_06 (coord C12), ENET_CRS_DV */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_CRS_DV_PERIPHERAL                              ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_CRS_DV_SIGNAL                            enet_rx_en   /*!< Signal name */

/* GPIO_B1_11 (coord C13), ENET_RXER */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_RXER_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_RXER_SIGNAL                              enet_rx_er   /*!< Signal name */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_RXD1_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_RXD1_SIGNAL                            enet_rx_data   /*!< Signal name */
#define BOARD_ENET1PINS_ENET_RXD1_CHANNEL                                     1U   /*!< Signal channel */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET_RXD0_PERIPHERAL                                ENET   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET_RXD0_SIGNAL                            enet_rx_data   /*!< Signal name */
#define BOARD_ENET1PINS_ENET_RXD0_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_AD_B0_14 (coord H14), CAN2_TX/U12[1]/ENET1_INT/CAN2_TX/U12[1]/CAN2_TX/U12[1] */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET1_INT_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET1_INT_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_ENET1PINS_ENET1_INT_CHANNEL                                    14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENET1PINS_ENET1_INT_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_ENET1PINS_ENET1_INT_GPIO_PIN                                   14U   /*!< GPIO pin number */
#define BOARD_ENET1PINS_ENET1_INT_GPIO_PIN_MASK                      (1U << 14U)   /*!< GPIO pin mask */
#define BOARD_ENET1PINS_ENET1_INT_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_ENET1PINS_ENET1_INT_PIN                                        14U   /*!< PORT pin number */
#define BOARD_ENET1PINS_ENET1_INT_PIN_MASK                           (1U << 14U)   /*!< PORT pin mask */

/* GPIO_B1_12 (coord D13), SD_CD_SW/ENET1_RST/SD_CD_SW/SD_CD_SW */
/* Routed pin properties */
#define BOARD_ENET1PINS_ENET1_RST_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_ENET1PINS_ENET1_RST_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_ENET1PINS_ENET1_RST_CHANNEL                                    28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENET1PINS_ENET1_RST_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_ENET1PINS_ENET1_RST_INIT_GPIO_VALUE                             1U   /*!< GPIO output initial state */
#define BOARD_ENET1PINS_ENET1_RST_GPIO_PIN                                   28U   /*!< GPIO pin number */
#define BOARD_ENET1PINS_ENET1_RST_GPIO_PIN_MASK                      (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_ENET1PINS_ENET1_RST_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_ENET1PINS_ENET1_RST_PIN                                        28U   /*!< PORT pin number */
#define BOARD_ENET1PINS_ENET1_RST_PIN_MASK                           (1U << 28U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_Enet1Pins(void);

#define BOARD_ENET2PINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x80000000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_ENET2PINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x04U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B0_00 (coord D7), LCDIF_CLK */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_CLK_PERIPHERAL                               ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_CLK_SIGNAL                                enet_mdc   /*!< Signal name */

/* GPIO_B1_15 (coord B14), USB_HOST_PWR/BACKLIGHT_CTL */
/* Routed pin properties */
#define BOARD_ENET2PINS_BACKLIGHT_CTL_PERIPHERAL                           ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_BACKLIGHT_CTL_SIGNAL                        enet_tx_data   /*!< Signal name */
#define BOARD_ENET2PINS_BACKLIGHT_CTL_CHANNEL                                 1U   /*!< Signal channel */

/* GPIO_B0_14 (coord E10), LCDIF_D10/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_D10_PERIPHERAL                               ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_D10_SIGNAL                              enet_tx_en   /*!< Signal name */

/* GPIO_B1_14 (coord C14), SD0_VSELECT */
/* Routed pin properties */
#define BOARD_ENET2PINS_SD0_VSELECT_PERIPHERAL                             ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_SD0_VSELECT_SIGNAL                          enet_tx_data   /*!< Signal name */
#define BOARD_ENET2PINS_SD0_VSELECT_CHANNEL                                   0U   /*!< Signal channel */

/* GPIO_SD_B0_01 (coord J3), J24_3_CS */
/* Routed pin properties */
#define BOARD_ENET2PINS_SD1_CLK_PERIPHERAL                                 ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_SD1_CLK_SIGNAL                               enet_tx_clk   /*!< Signal name */

/* GPIO_B0_01 (coord E7), LCDIF_ENABLE */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_ENABLE_PERIPHERAL                            ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_ENABLE_SIGNAL                            enet_mdio   /*!< Signal name */

/* GPIO_B0_10 (coord D9), LCDIF_D6/BT_CFG[6] */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_D6_PERIPHERAL                                ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_D6_SIGNAL                                 enet_crs   /*!< Signal name */

/* GPIO_B1_00 (coord A11), LCDIF_D12 */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_D12_PERIPHERAL                               ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_D12_SIGNAL                              enet_rx_er   /*!< Signal name */

/* GPIO_B1_02 (coord C11), LCDIF_D14 */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_D14_PERIPHERAL                               ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_D14_SIGNAL                            enet_rx_data   /*!< Signal name */
#define BOARD_ENET2PINS_LCDIF_D14_CHANNEL                                     1U   /*!< Signal channel */

/* GPIO_B1_01 (coord B11), LCDIF_D13 */
/* Routed pin properties */
#define BOARD_ENET2PINS_LCDIF_D13_PERIPHERAL                               ENET2   /*!< Peripheral name */
#define BOARD_ENET2PINS_LCDIF_D13_SIGNAL                            enet_rx_data   /*!< Signal name */
#define BOARD_ENET2PINS_LCDIF_D13_CHANNEL                                     0U   /*!< Signal channel */

/* GPIO_B0_02 (coord E8), LCDIF_HSYNC/ENET2_INT/LCDIF_HSYNC/LCDIF_HSYNC */
/* Routed pin properties */
#define BOARD_ENET2PINS_ENET2_INT_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_ENET2PINS_ENET2_INT_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_ENET2PINS_ENET2_INT_CHANNEL                                     2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENET2PINS_ENET2_INT_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_ENET2PINS_ENET2_INT_GPIO_PIN                                    2U   /*!< GPIO pin number */
#define BOARD_ENET2PINS_ENET2_INT_GPIO_PIN_MASK                       (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_ENET2PINS_ENET2_INT_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_ENET2PINS_ENET2_INT_PIN                                         2U   /*!< PORT pin number */
#define BOARD_ENET2PINS_ENET2_INT_PIN_MASK                            (1U << 2U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (coord J14), SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13]/ENET2_RST/SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13]/SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13] */
/* Routed pin properties */
#define BOARD_ENET2PINS_ENET2_RST_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_ENET2PINS_ENET2_RST_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_ENET2PINS_ENET2_RST_CHANNEL                                    31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_ENET2PINS_ENET2_RST_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_ENET2PINS_ENET2_RST_GPIO_PIN                                   31U   /*!< GPIO pin number */
#define BOARD_ENET2PINS_ENET2_RST_GPIO_PIN_MASK                      (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_ENET2PINS_ENET2_RST_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_ENET2PINS_ENET2_RST_PIN                                        31U   /*!< PORT pin number */
#define BOARD_ENET2PINS_ENET2_RST_PIN_MASK                           (1U << 31U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_Enet2Pins(void);

/* USB_OTG1_DP (coord L8), OTG1_DP */
/* Routed pin properties */
#define BOARD_USBOTG_PINS_OTG1_DP_PERIPHERAL                                USB1   /*!< Peripheral name */
#define BOARD_USBOTG_PINS_OTG1_DP_SIGNAL                             usb_otg1_dp   /*!< Signal name */

/* USB_OTG1_DN (coord M8), OTG1_DN */
/* Routed pin properties */
#define BOARD_USBOTG_PINS_OTG1_DN_PERIPHERAL                                USB1   /*!< Peripheral name */
#define BOARD_USBOTG_PINS_OTG1_DN_SIGNAL                             usb_otg1_dn   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_USBOTG_Pins(void);

#define BOARD_UART_DEBUG_PINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x100000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B1_04 (coord L12), GPIO! */
/* Routed pin properties */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PERIPHERAL                       GPIO1   /*!< Peripheral name */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_CHANNEL                            20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_GPIO                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_INIT_GPIO_VALUE                     0U   /*!< GPIO output initial state */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_GPIO_PIN                           20U   /*!< GPIO pin number */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_GPIO_PIN_MASK              (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PORT                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN                                20U   /*!< PORT pin number */
#define BOARD_UART_DEBUG_PINS_UART1_TX_EN_PIN_MASK                   (1U << 20U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_UART_Debug_Pins(void);

#define BOARD_LPSPI2_PINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x0200U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_SD_B1_06 (coord L3), DisableQSPI */
/* Routed pin properties */
#define BOARD_LPSPI2_PINS_FlexSPI_SS0_PERIPHERAL                          LPSPI2   /*!< Peripheral name */
#define BOARD_LPSPI2_PINS_FlexSPI_SS0_SIGNAL                                PCS0   /*!< Signal name */

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
/* Routed pin properties */
#define BOARD_LPSPI2_PINS_FlexSPI_CLK_PERIPHERAL                          LPSPI2   /*!< Peripheral name */
#define BOARD_LPSPI2_PINS_FlexSPI_CLK_SIGNAL                                 SCK   /*!< Signal name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
/* Routed pin properties */
#define BOARD_LPSPI2_PINS_FlexSPI_D0_A_PERIPHERAL                         LPSPI2   /*!< Peripheral name */
#define BOARD_LPSPI2_PINS_FlexSPI_D0_A_SIGNAL                                SDO   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
/* Routed pin properties */
#define BOARD_LPSPI2_PINS_FlexSPI_D1_A_PERIPHERAL                         LPSPI2   /*!< Peripheral name */
#define BOARD_LPSPI2_PINS_FlexSPI_D1_A_SIGNAL                                SDI   /*!< Signal name */

/* GPIO_B0_09 (coord C9), LCDIF_D5/BT_CFG[5]/SPI_Flash_WP/LCDIF_D5/BT_CFG[5]/LCDIF_D5/BT_CFG[5] */
/* Routed pin properties */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_PERIPHERAL                          GPIO2   /*!< Peripheral name */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_CHANNEL                                9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_GPIO                                GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_GPIO_PIN                               9U   /*!< GPIO pin number */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_GPIO_PIN_MASK                  (1U << 9U)   /*!< GPIO pin mask */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_PORT                                GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_PIN                                    9U   /*!< PORT pin number */
#define BOARD_LPSPI2_PINS_SPI_Flash_WP_PIN_MASK                       (1U << 9U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_LPSPI2_Pins(void);

#define BOARD_I2C1_PINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0800U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_11 (coord G10), INTR */
/* Routed pin properties */
#define BOARD_I2C1_PINS_Interrupt_Temp_PERIPHERAL                          GPIO1   /*!< Peripheral name */
#define BOARD_I2C1_PINS_Interrupt_Temp_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_I2C1_PINS_Interrupt_Temp_CHANNEL                               11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_I2C1_PINS_Interrupt_Temp_GPIO                                GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_I2C1_PINS_Interrupt_Temp_GPIO_PIN                              11U   /*!< GPIO pin number */
#define BOARD_I2C1_PINS_Interrupt_Temp_GPIO_PIN_MASK                 (1U << 11U)   /*!< GPIO pin mask */
#define BOARD_I2C1_PINS_Interrupt_Temp_PORT                                GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_I2C1_PINS_Interrupt_Temp_PIN                                   11U   /*!< PORT pin number */
#define BOARD_I2C1_PINS_Interrupt_Temp_PIN_MASK                      (1U << 11U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_I2C1_Pins(void);

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
/* Routed pin properties */
#define BOARD_I2C2_PINS_FlexSPI_D3_A_PERIPHERAL                           LPI2C2   /*!< Peripheral name */
#define BOARD_I2C2_PINS_FlexSPI_D3_A_SIGNAL                                  SCL   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
/* Routed pin properties */
#define BOARD_I2C2_PINS_FlexSPI_D2_A_PERIPHERAL                           LPI2C2   /*!< Peripheral name */
#define BOARD_I2C2_PINS_FlexSPI_D2_A_SIGNAL                                  SDA   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_I2C2_Pins(void);

#define BOARD_LPSPI1_LED_PINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0FE0800CU /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_LPSPI1_LED_PINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x080000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define BOARD_LPSPI1_LED_PINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x50U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_AD_B1_12 (coord H12), PCS0/SAI1_RXD/CSI_D5/J35[5]/U13[16]/SAI1_RXD/CSI_D5/J35[5]/U13[16] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_CSI_D5_PERIPHERAL                           LPSPI3   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_CSI_D5_SIGNAL                                 PCS0   /*!< Signal name */

/* GPIO_AD_B0_00 (coord M14), SCK */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DF0_PERIPHERAL                   LPSPI3   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DF0_SIGNAL                          SCK   /*!< Signal name */

/* GPIO_AD_B1_10 (coord L13), SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1]/LED_Driver_LE/SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1]/SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_PERIPHERAL                     GPIO6   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_SIGNAL                       gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_CHANNEL                          26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_GPIO                           GPIO6   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_INIT_GPIO_VALUE                   1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_GPIO_PIN                         26U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_GPIO_PIN_MASK            (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_PORT                           GPIO6   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_PIN                              26U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_LE_PIN_MASK                 (1U << 26U)   /*!< PORT pin mask */

/* GPIO_SD_B1_04 (coord P2), FlexSPI_CLK_B/LED_Driver_OE_R/FlexSPI_CLK_B/FlexSPI_CLK_B */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PERIPHERAL                   GPIO8   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_CHANNEL                         4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_GPIO                         GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_INIT_GPIO_VALUE                 1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_GPIO_PIN                        4U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_GPIO_PIN_MASK           (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PORT                         GPIO8   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN                             4U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_R_PIN_MASK                (1U << 4U)   /*!< PORT pin mask */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11]/LED_Driver_OE_G/SAI1_MCLK/CSI_D8/J35[11]/SAI1_MCLK/CSI_D8/J35[11] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PERIPHERAL                   GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_CHANNEL                        25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_GPIO                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_INIT_GPIO_VALUE                 1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_GPIO_PIN                       25U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_GPIO_PIN_MASK          (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PORT                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN                            25U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_G_PIN_MASK               (1U << 25U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (coord K12), CSI_MCLK/J35[12]/J23[4]/LED_Driver_OE_B/CSI_MCLK/J35[12]/J23[4]/CSI_MCLK/J35[12]/J23[4] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PERIPHERAL                   GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_CHANNEL                        21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_GPIO                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_INIT_GPIO_VALUE                 1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_GPIO_PIN                       21U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_GPIO_PIN_MASK          (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PORT                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN                            21U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_OE_B_PIN_MASK               (1U << 21U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2]/LED_Driver_EF_Int/SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2]/SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PERIPHERAL                 GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_SIGNAL                   gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_CHANNEL                      27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_GPIO                       GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_GPIO_PIN                     27U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_GPIO_PIN_MASK        (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PORT                       GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN                          27U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_EF_Int_PIN_MASK             (1U << 27U)   /*!< PORT pin mask */

/* GPIO_B1_03 (coord D11), LCDIF_D15/LED_Driver_DetMode/LCDIF_D15/LCDIF_D15 */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_PERIPHERAL                GPIO2   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_SIGNAL                  gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_CHANNEL                     19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_GPIO                      GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_INIT_GPIO_VALUE              1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_GPIO_PIN                    19U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_GPIO_PIN_MASK       (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_PORT                      GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_PIN                         19U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_DetMode_PIN_MASK            (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B0_15 (coord L10), CAN2_RX/U12[4]/LED_Driver_GrdlDelay/CAN2_RX/U12[4]/CAN2_RX/U12[4] */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PERIPHERAL              GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_SIGNAL                gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_CHANNEL                   15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_GPIO                    GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_INIT_GPIO_VALUE            0U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_GPIO_PIN                  15U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_GPIO_PIN_MASK     (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PORT                    GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN                       15U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_Driver_GrdlDelay_PIN_MASK          (1U << 15U)   /*!< PORT pin mask */

/* GPIO_AD_B0_02 (coord M11), J24_2_LE */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_LE_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_LE_CHANNEL                                  2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_LE_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_LE_INIT_GPIO_VALUE                          0U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_LE_GPIO_PIN                                 2U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_LE_GPIO_PIN_MASK                    (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PIN                                      2U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_LE_PIN_MASK                         (1U << 2U)   /*!< PORT pin mask */

/* GPIO_AD_B0_03 (coord G11), J24_1_OEn */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PERIPHERAL                            GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_OE_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_LED_OE_CHANNEL                                  3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_LED_OE_GPIO                                  GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_OE_INIT_GPIO_VALUE                          1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_LED_OE_GPIO_PIN                                 3U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_LED_OE_GPIO_PIN_MASK                    (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PORT                                  GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PIN                                      3U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_LED_OE_PIN_MASK                         (1U << 3U)   /*!< PORT pin mask */

/* GPIO_SD_B0_01 (coord J3), J24_3_CS */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_CSn_PERIPHERAL                          LPSPI1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_CSn_SIGNAL                                PCS0   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J1), J24_4_SDO */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_SDO_PERIPHERAL                          LPSPI1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_SDO_SIGNAL                                 SDO   /*!< Signal name */

/* GPIO_SD_B0_03 (coord K1), J24_5_SDI */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_SDI_PERIPHERAL                          LPSPI1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_SDI_SIGNAL                                 SDI   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), J24_6_CLK */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_LED_CLK_PERIPHERAL                          LPSPI1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_LED_CLK_SIGNAL                                 SCK   /*!< Signal name */

/* GPIO_AD_B1_07 (coord K10), A0 */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_A0_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_A0_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_A0_CHANNEL                                     23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_A0_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A0_INIT_GPIO_VALUE                              0U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_A0_GPIO_PIN                                    23U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_A0_GPIO_PIN_MASK                       (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_A0_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A0_PIN                                         23U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_A0_PIN_MASK                            (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (coord J12), A1 */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_A1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_A1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_A1_CHANNEL                                     22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_A1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A1_INIT_GPIO_VALUE                              0U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_A1_GPIO_PIN                                    22U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_A1_GPIO_PIN_MASK                       (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_A1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A1_PIN                                         22U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_A1_PIN_MASK                            (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), A2 */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_A2_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_A2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_A2_CHANNEL                                     24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_A2_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A2_INIT_GPIO_VALUE                              0U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_A2_GPIO_PIN                                    24U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_A2_GPIO_PIN_MASK                       (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_A2_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_A2_PIN                                         24U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_A2_PIN_MASK                            (1U << 24U)   /*!< PORT pin mask */

/* GPIO_SD_B1_06 (coord L3), DisableQSPI */
/* Routed pin properties */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PERIPHERAL                       GPIO8   /*!< Peripheral name */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_CHANNEL                             6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_GPIO                             GPIO8   /*!< GPIO peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_INIT_GPIO_VALUE                     1U   /*!< GPIO output initial state */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_GPIO_PIN                            6U   /*!< GPIO pin number */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_GPIO_PIN_MASK               (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PORT                             GPIO8   /*!< PORT peripheral base pointer */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN                                 6U   /*!< PORT pin number */
#define BOARD_LPSPI1_LED_PINS_FlexSPI_SS0_PIN_MASK                    (1U << 6U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_LPSPI1_LED_Pins(void);

#define BOARD_GPIOBUFANDMUX_TODO_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x01C00000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_GPIOBUFANDMUX_TODO_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x81E0U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B0_05 (coord B8), LCDIF_D1/BT_CFG[1] */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_CHANNEL                             5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_GPIO_PIN                            5U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_GPIO_PIN_MASK               (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_PIN                                 5U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D1_PIN_MASK                    (1U << 5U)   /*!< PORT pin mask */

/* GPIO_B0_06 (coord A8), LCDIF_D2/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_CHANNEL                             6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_GPIO_PIN                            6U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_GPIO_PIN_MASK               (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_PIN                                 6U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D2_PIN_MASK                    (1U << 6U)   /*!< PORT pin mask */

/* GPIO_B0_07 (coord A9), LCDIF_D3/BT_CFG[3] */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_CHANNEL                             7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_GPIO_PIN                            7U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_GPIO_PIN_MASK               (1U << 7U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_PIN                                 7U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D3_PIN_MASK                    (1U << 7U)   /*!< PORT pin mask */

/* GPIO_B0_08 (coord B9), LCDIF_D4/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_CHANNEL                             8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_GPIO_PIN                            8U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_GPIO_PIN_MASK               (1U << 8U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_PIN                                 8U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D4_PIN_MASK                    (1U << 8U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (coord J12), A1 */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_PERIPHERAL                      GPIO1   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_CHANNEL                           22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_GPIO                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_GPIO_PIN                          22U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_GPIO_PIN_MASK             (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_PORT                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_PIN                               22U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_VSYNC_PIN_MASK                  (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (coord K10), A0 */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_PERIPHERAL                      GPIO1   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_CHANNEL                           23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_GPIO                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_GPIO_PIN                          23U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_GPIO_PIN_MASK             (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_PORT                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_PIN                               23U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_HSYNC_PIN_MASK                  (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), A2 */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_PERIPHERAL                         GPIO1   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_CHANNEL                              24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_GPIO                               GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_GPIO_PIN                             24U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_GPIO_PIN_MASK                (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_PORT                               GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_PIN                                  24U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_CSI_D9_PIN_MASK                     (1U << 24U)   /*!< PORT pin mask */

/* GPIO_B0_15 (coord E11), LCDIF_D11/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_PERIPHERAL                      GPIO2   /*!< Peripheral name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_CHANNEL                           15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_GPIO                            GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_GPIO_PIN                          15U   /*!< GPIO pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_GPIO_PIN_MASK             (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_PORT                            GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_PIN                               15U   /*!< PORT pin number */
#define BOARD_GPIOBUFANDMUX_TODO_LCDIF_D11_PIN_MASK                  (1U << 15U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 * 
 * Swamy : TODO : Init
 *
 */
void Board_GPIOBufAndMux_TODO(void);

/* GPIO_AD_B1_02 (coord L11), SPDIF_OUT/J22[7] */
/* Routed pin properties */
#define BOARD_ADC1_PINS_SPDIF_OUT_PERIPHERAL                                ADC1   /*!< Peripheral name */
#define BOARD_ADC1_PINS_SPDIF_OUT_SIGNAL                                      IN   /*!< Signal name */
#define BOARD_ADC1_PINS_SPDIF_OUT_CHANNEL                                     7U   /*!< Signal channel */

/* GPIO_AD_B1_03 (coord M12), SPDIF_IN/J22[8] */
/* Routed pin properties */
#define BOARD_ADC1_PINS_SPDIF_IN_PERIPHERAL                                 ADC1   /*!< Peripheral name */
#define BOARD_ADC1_PINS_SPDIF_IN_SIGNAL                                       IN   /*!< Signal name */
#define BOARD_ADC1_PINS_SPDIF_IN_CHANNEL                                      8U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_ADC1_Pins(void);

#define HWREVISIONID_GPIO_PINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x08U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define HWREVISIONID_GPIO_PINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x030007U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */

/* GPIO_B0_03 (coord D8), LCDIF_VSYNC/LCDIF_VSYNC/HW1/LCDIF_VSYNC/LCDIF_VSYNC/LCDIF_VSYNC/LCDIF_VSYNC */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW1_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW1_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW1_CHANNEL                                    3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW1_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW1_GPIO_PIN                                   3U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW1_GPIO_PIN_MASK                      (1U << 3U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW1_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW1_PIN                                        3U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW1_PIN_MASK                           (1U << 3U)   /*!< PORT pin mask */

/* GPIO_SD_B0_04 (coord H2), SD1_D2/SD1_D2/HW2/SD1_D2/SD1_D2/SD1_D2/SD1_D2 */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW2_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW2_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW2_CHANNEL                                   16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW2_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW2_GPIO_PIN                                  16U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW2_GPIO_PIN_MASK                     (1U << 16U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW2_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW2_PIN                                       16U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW2_PIN_MASK                          (1U << 16U)   /*!< PORT pin mask */

/* GPIO_SD_B0_05 (coord J2), SD1_D3/SD1_D3/HW3/SD1_D3/SD1_D3/SD1_D3/SD1_D3 */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW3_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW3_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW3_CHANNEL                                   17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW3_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW3_GPIO_PIN                                  17U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW3_GPIO_PIN_MASK                     (1U << 17U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW3_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW3_PIN                                       17U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW3_PIN_MASK                          (1U << 17U)   /*!< PORT pin mask */

/* GPIO_SD_B1_00 (coord L5), FlexSPI_D3_B/FlexSPI_D3_B/HW4/FlexSPI_D3_B/FlexSPI_D3_B/FlexSPI_D3_B/FlexSPI_D3_B */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW4_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW4_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW4_CHANNEL                                    0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW4_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW4_GPIO_PIN                                   0U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW4_GPIO_PIN_MASK                      (1U << 0U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW4_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW4_PIN                                        0U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW4_PIN_MASK                           (1U << 0U)   /*!< PORT pin mask */

/* GPIO_SD_B1_01 (coord M5), FlexSPI_D2_B */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW5_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW5_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW5_CHANNEL                                    1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW5_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW5_GPIO_PIN                                   1U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW5_GPIO_PIN_MASK                      (1U << 1U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW5_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW5_PIN                                        1U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW5_PIN_MASK                           (1U << 1U)   /*!< PORT pin mask */

/* GPIO_SD_B1_02 (coord M3), FlexSPI_D1_B */
/* Routed pin properties */
#define HWREVISIONID_GPIO_PINS_HW6_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define HWREVISIONID_GPIO_PINS_HW6_SIGNAL                                gpio_io   /*!< Signal name */
#define HWREVISIONID_GPIO_PINS_HW6_CHANNEL                                    2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define HWREVISIONID_GPIO_PINS_HW6_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW6_GPIO_PIN                                   2U   /*!< GPIO pin number */
#define HWREVISIONID_GPIO_PINS_HW6_GPIO_PIN_MASK                      (1U << 2U)   /*!< GPIO pin mask */
#define HWREVISIONID_GPIO_PINS_HW6_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define HWREVISIONID_GPIO_PINS_HW6_PIN                                        2U   /*!< PORT pin number */
#define HWREVISIONID_GPIO_PINS_HW6_PIN_MASK                           (1U << 2U)   /*!< PORT pin mask */

/*!
 * @brief "GPIO (9)
 * - PCB Revision (3bits)
 * - Assembly Version(3bits)
 * - Assembly Revision(3bits) "
 *
 */
void HWRevisionID_GPIO_PIns(void);

#define BOARD_INITCSI_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x10U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B1_08 (coord H13), A2 */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D9_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D9_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D9_CHANNEL                                          9U   /*!< Signal channel */

/* GPIO_AD_B1_12 (coord H12), PCS0/SAI1_RXD/CSI_D5/J35[5]/U13[16]/SAI1_RXD/CSI_D5/J35[5]/U13[16] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_D5_PERIPHERAL                                      CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_D5_SIGNAL                                     csi_data   /*!< Signal name */
#define BOARD_INITCSI_CSI_D5_CHANNEL                                          5U   /*!< Signal channel */

/* GPIO_AD_B1_06 (coord J12), A1 */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_VSYNC_PERIPHERAL                                   CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_VSYNC_SIGNAL                                 csi_vsync   /*!< Signal name */

/* GPIO_AD_B1_07 (coord K10), A0 */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_HSYNC_PERIPHERAL                                   CSI   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_HSYNC_SIGNAL                                 csi_hsync   /*!< Signal name */

/* GPIO_AD_B1_00 (coord J11), I2C1_SCL/CSI_I2C_SCL/J35[20]/J23[6]/U13[17]/U32[4] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_I2C_SCL_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_I2C_SCL_SIGNAL                                     SCL   /*!< Signal name */

/* GPIO_AD_B1_01 (coord K11), I2C1_SDA/CSI_I2C_SDA/J35[22]/J23[5]/U13[18]/U32[6] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_I2C_SDA_PERIPHERAL                              LPI2C1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_I2C_SDA_SIGNAL                                     SDA   /*!< Signal name */

/* GPIO_AD_B0_04 (coord F11), CSI_PWDN/J35[17]/BOOT_MODE[0] */
/* Routed pin properties */
#define BOARD_INITCSI_CSI_PWDN_PERIPHERAL                                  GPIO1   /*!< Peripheral name */
#define BOARD_INITCSI_CSI_PWDN_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITCSI_CSI_PWDN_CHANNEL                                        4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITCSI_CSI_PWDN_GPIO                                        GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITCSI_CSI_PWDN_GPIO_PIN                                       4U   /*!< GPIO pin number */
#define BOARD_INITCSI_CSI_PWDN_GPIO_PIN_MASK                          (1U << 4U)   /*!< GPIO pin mask */
#define BOARD_INITCSI_CSI_PWDN_PORT                                        GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITCSI_CSI_PWDN_PIN                                            4U   /*!< PORT pin number */
#define BOARD_INITCSI_CSI_PWDN_PIN_MASK                               (1U << 4U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCSI(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
